const codexes = [
  'Adepta Sororitas',
  'Adeptus Custodes',
  'Adeptus Mechanicus',
  'Aeldari',
  'Astra Militarum',
  'Black Templars',
  'Blood Angels',
  'Chaos Daemons',
  'Chaos Knights',
  'Chaos Space Marines',
  "Emperor's Children",
  'Dark Angels',
  'Death Guard',
  'Drukhari',
  'Genestealer Cults',
  'Grey Knights',
  'Imperial Agents',
  'Imperial Knights',
  'Leagues Of Votann',
  'Necrons',
  'Orks',
  'Space Marines',
  'Space Wolves',
  "T'au Empire",
  'Thousand Sons',
  'Tyranids',
  'World Eaters'
] as const

export default codexes
