import {
  adeptaSororitasIcon,
  adeptusAstartesIcon,
  adeptusMechanicusIcon,
  aeldariIcon,
  astraMilitarumIcon,
  blackTemplarsIcon,
  bloodAngelsIcon,
  bloodRavensIcon,
  chaosDaemonsIcon,
  chaosSpaceMarinesIcon,
  darkAngelsIcon,
  deathGuardIcon,
  deathwatchIcon,
  drukhariIcon,
  emperorsChildrenIcon,
  genestealerCultsIcon,
  greyKnightsIcon,
  imperialFistsIcon,
  inquisitionIcon,
  necronsIcon,
  orksIcon,
  spaceWolvesIcon,
  tauIcon,
  thousandSonsIcon,
  tyranidsIcon,
  worldEatersIcon
} from 'appdeptus/assets'
import { CodexName } from 'appdeptus/models'

const mapCodexNameToIcon = {
  [CodexName.ADEPTA_SORORITAS]: adeptaSororitasIcon,
  [CodexName.ADEPTUS_ASTARTES]: adeptusAstartesIcon,
  [CodexName.ADEPTUS_MECHANICUS]: adeptusMechanicusIcon,
  [CodexName.AELDARI]: aeldariIcon,
  [CodexName.ASTRA_MILITARUM]: astraMilitarumIcon,
  [CodexName.BLACK_TEMPLARS]: blackTemplarsIcon,
  [CodexName.BLOOD_ANGELS]: bloodAngelsIcon,
  [CodexName.BLOOD_RAVENS]: bloodRavensIcon,
  [CodexName.CHAOS_DAEMONS]: chaosDaemonsIcon,
  [CodexName.CHAOS_SPACE_MARINES]: chaosSpaceMarinesIcon,
  [CodexName.DARK_ANGELS]: darkAngelsIcon,
  [CodexName.DEATH_GUARD]: deathGuardIcon,
  [CodexName.DEATHWATCH]: deathwatchIcon,
  [CodexName.DRUKHARI]: drukhariIcon,
  [CodexName.EMPERORS_CHILDREN]: emperorsChildrenIcon,
  [CodexName.GENESTEALER_CULTS]: genestealerCultsIcon,
  [CodexName.GREY_KNIGHTS]: greyKnightsIcon,
  [CodexName.IMPERIAL_FISTS]: imperialFistsIcon,
  [CodexName.INQUISITION]: inquisitionIcon,
  [CodexName.NECRONS]: necronsIcon,
  [CodexName.ORKS]: orksIcon,
  [CodexName.SPACE_WOLVES]: spaceWolvesIcon,
  [CodexName.TAU]: tauIcon,
  [CodexName.THOUSAND_SONS]: thousandSonsIcon,
  [CodexName.TYRANIDS]: tyranidsIcon,
  [CodexName.WORLD_EATERS]: worldEatersIcon
} as const

export { mapCodexNameToIcon }
