import {
  adeptaSororitasIcon,
  adeptusCustodesIcon,
  adeptusMechanicusIcon,
  aeldariIcon,
  agentsOfTheImperiumIcon,
  astraMilitarumIcon,
  blackTemplarsIcon,
  bloodAngelsIcon,
  chaosDaemonsIcon,
  chaosSpaceMarinesIcon,
  darkAngelsIcon,
  deathGuardIcon,
  drukhariIcon,
  genestealerCultsIcon,
  greyKnightsIcon,
  leaguesOfVotannIcon,
  necronsIcon,
  orksIcon,
  spaceMarinesIcon,
  spaceWolvesIcon,
  tauEmpireIcon,
  thousandSonsIcon,
  tyranidsIcon,
  worldEatersIcon
} from 'appdeptus/assets'
import { CodexName } from 'appdeptus/models'

const mapCodexNameToIcon: Record<CodexName, string> = {
  [CodexName.ADEPTA_SORORITAS]: adeptaSororitasIcon,
  [CodexName.ADEPTUS_CUSTODES]: adeptusCustodesIcon,
  [CodexName.ADEPTUS_MECHANICUS]: adeptusMechanicusIcon,
  [CodexName.AELDARI]: aeldariIcon,
  [CodexName.AGENTS_OF_THE_IMPERIUM]: agentsOfTheImperiumIcon,
  [CodexName.ASTRA_MILITARUM]: astraMilitarumIcon,
  [CodexName.BLACK_TEMPLARS]: blackTemplarsIcon,
  [CodexName.BLOOD_ANGELS]: bloodAngelsIcon,
  [CodexName.CHAOS_DAEMONS]: chaosDaemonsIcon,
  [CodexName.CHAOS_SPACE_MARINES]: chaosSpaceMarinesIcon,
  [CodexName.DARK_ANGELS]: darkAngelsIcon,
  [CodexName.DEATH_GUARD]: deathGuardIcon,
  [CodexName.DRUKHARI]: drukhariIcon,
  [CodexName.GENESTEALER_CULTS]: genestealerCultsIcon,
  [CodexName.GREY_KNIGHTS]: greyKnightsIcon,
  [CodexName.LEAGUES_OF_VOTANN]: leaguesOfVotannIcon,
  [CodexName.NECRONS]: necronsIcon,
  [CodexName.ORKS]: orksIcon,
  [CodexName.SPACE_MARINES]: spaceMarinesIcon,
  [CodexName.SPACE_WOLVES]: spaceWolvesIcon,
  [CodexName.TAU_EMPIRE]: tauEmpireIcon,
  [CodexName.THOUSAND_SONS]: thousandSonsIcon,
  [CodexName.TYRANIDS]: tyranidsIcon,
  [CodexName.WORLD_EATERS]: worldEatersIcon
} as const

export default mapCodexNameToIcon
